export const PRESENCE_IPC_CHANNELS = {
  CONNECT: 'teacher:presence:connect',
  DISCONNECT: 'teacher:presence:disconnect',
  GET_STATE: 'teacher:presence:get-state',
  ACCEPT_SESSION: 'teacher:presence:accept-session',
  REJECT_SESSION: 'teacher:presence:reject-session',
  END_SESSION: 'teacher:presence:end-session',
  STATE_CHANGED: 'teacher:presence:state-changed',
  WEBRTC_SEND_OFFER: 'teacher:webrtc:send-offer',
  WEBRTC_SEND_ANSWER: 'teacher:webrtc:send-answer',
  WEBRTC_SEND_ICE: 'teacher:webrtc:send-ice-candidate',
  WEBRTC_OFFER: 'teacher:webrtc:offer',
  WEBRTC_ANSWER: 'teacher:webrtc:answer',
  WEBRTC_ICE: 'teacher:webrtc:ice-candidate',
  SCREEN_SHARE_STARTED: 'teacher:screen-share:started',
  SCREEN_SHARE_STOPPED: 'teacher:screen-share:stopped',
  REMOTE_CONTROL_REQUEST: 'teacher:remote-control:request',
  REMOTE_CONTROL_MOUSE: 'teacher:remote-control:mouse',
  REMOTE_CONTROL_KEYBOARD: 'teacher:remote-control:keyboard',
  REMOTE_CONTROL_STOP: 'teacher:remote-control:stop',
} as const;
