services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - professor-connect-node-modules:/app/node_modules

volumes:
  professor-connect-node-modules:
