export const SESSION_IPC_CHANNELS = {
  GET_TEACHERS: 'student:session:get-teachers',
  REQUEST: 'student:session:request',
  GET_STATE: 'student:session:get-state',
  END: 'student:session:end',
  STATE_CHANGED: 'student:session:state-changed',
  WEBRTC_SEND_ANSWER: 'student:webrtc:send-answer',
  WEBRTC_SEND_OFFER: 'student:webrtc:send-offer',
  WEBRTC_SEND_ICE: 'student:webrtc:send-ice-candidate',
  SCREEN_SHARE_START: 'student:screen-share:start',
  SCREEN_SHARE_STOP: 'student:screen-share:stop',
  SCREEN_CAPTURE_PREPARE_ALL: 'student:screen-capture:prepare-all',
  WEBRTC_OFFER: 'student:webrtc:offer',
  WEBRTC_ANSWER: 'student:webrtc:answer',
  WEBRTC_ICE: 'student:webrtc:ice-candidate',
  REMOTE_CONTROL_APPROVE: 'student:remote-control:approve',
  REMOTE_CONTROL_DENY: 'student:remote-control:deny',
  REMOTE_CONTROL_STOP: 'student:remote-control:stop',
} as const;
