import type { StateTransitionDefinition } from '@professor-connect/services/state-machine';

import { EndToEndState } from './integration.types.js';

export enum EndToEndEventType {
  CONNECTION_ESTABLISHED = 'integration.connection-established',
  PRESENCE_REGISTERED = 'integration.presence-registered',
  STUDENTS_UPDATED = 'integration.students-updated',
  REQUEST_CREATED = 'integration.request-created',
  REQUEST_RECEIVED = 'integration.request-received',
  REQUEST_ACCEPTED = 'integration.request-accepted',
  REQUEST_REJECTED = 'integration.request-rejected',
  SESSION_CREATED = 'integration.session-created',
  CALL_CREATED = 'integration.call-created',
  SIGNALING_STARTED = 'integration.signaling-started',
  WEBRTC_CONNECTED = 'integration.webrtc-connected',
  AUDIO_STARTED = 'integration.audio-started',
  VIDEO_STARTED = 'integration.video-started',
  SCREEN_SHARING_STARTED = 'integration.screen-sharing-started',
  CONNECTION_LOST = 'integration.connection-lost',
  RECONNECTED = 'integration.reconnected',
  ATTENDANCE_ENDED = 'integration.attendance-ended',
  RESOURCES_RELEASED = 'integration.resources-released',
  DISCONNECTED = 'integration.disconnected',
  FAILED = 'integration.failed',
}

const {
  DISCONNECTED,
  CONNECTING,
  CONNECTED,
  CALLING,
  PREPARING,
  IN_ATTENDANCE,
  SHARING,
  RECONNECTING,
  STOPPING,
  FAILED,
} = EndToEndState;

export const END_TO_END_STATE_TRANSITIONS: readonly StateTransitionDefinition<EndToEndState>[] = [
  { from: DISCONNECTED, to: CONNECTING },
  { from: FAILED, to: CONNECTING },
  { from: CONNECTING, to: CONNECTED },
  { from: CONNECTED, to: CALLING },
  { from: CONNECTED, to: PREPARING },
  { from: CALLING, to: PREPARING },
  { from: CALLING, to: CONNECTED },
  { from: PREPARING, to: IN_ATTENDANCE },
  { from: IN_ATTENDANCE, to: SHARING },
  { from: SHARING, to: IN_ATTENDANCE },
  { from: IN_ATTENDANCE, to: RECONNECTING },
  { from: SHARING, to: RECONNECTING },
  { from: RECONNECTING, to: IN_ATTENDANCE },
  { from: CONNECTED, to: STOPPING },
  { from: CALLING, to: STOPPING },
  { from: PREPARING, to: STOPPING },
  { from: IN_ATTENDANCE, to: STOPPING },
  { from: SHARING, to: STOPPING },
  { from: RECONNECTING, to: STOPPING },
  { from: STOPPING, to: CONNECTED },
  { from: STOPPING, to: DISCONNECTED },
  { from: CONNECTING, to: FAILED },
  { from: CONNECTED, to: FAILED },
  { from: CALLING, to: FAILED },
  { from: PREPARING, to: FAILED },
  { from: IN_ATTENDANCE, to: FAILED },
  { from: SHARING, to: FAILED },
  { from: RECONNECTING, to: FAILED },
  { from: STOPPING, to: FAILED },
];
